language: cpp

notifications:
  email: false

matrix:
  include:
    - os: linux
      compiler: g++-5
      env: COMPILER=g++ -std=c++11

script:
  - chmod 777 ./cpplint.py
  - ( for file in $(find . -name "*.cpp"); do ./cpplint.py $file || exit; done );
  - mkdir build && cd build
  - cmake .. && make
#  - ./executable
